/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.sindicoonline.frm;

import br.com.sindicoonline.DAO.Apto;
import br.com.sindicoonline.DAO.AptoDAO;
import br.com.sindicoonline.DAO.Bloco;
import br.com.sindicoonline.DAO.BlocoDAO;
import br.com.sindicoonline.DAO.Conexao;
import br.com.sindicoonline.DAO.Predio;
import br.com.sindicoonline.Utilits.Utilidades;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author klebe
 */
public class frmApto extends javax.swing.JInternalFrame {

    String opSAlvarEditar = "";
//    int nPredio = 0;

    public frmApto() {
        initComponents();
        lerTabela();
        try {
            populaComboPredio();
            populaELimpa();
        } catch (Exception e) {

        }

    }

    public void populaELimpa() {

        Utilidades util = new Utilidades();
        int nPredio = util.achaCodigoPredio((comboPredio.getSelectedItem().toString()));
        comboBloco.removeAllItems();
        populaComboBloco(nPredio);

    }

    public void lerTabela() {

        DefaultTableModel modelo = (DefaultTableModel) jtApto.getModel();
        modelo.setNumRows(0);
        Apto apto = new Apto();
        AptoDAO daoApto = new AptoDAO();

        for (Apto a : daoApto.readAptoListaComNome(apto)) {
            modelo.addRow(new Object[]{
                a.getIdApto(),
                a.getNumeroApto(),
                a.getBloco().getNumeroBloco(),
                a.getPredio().getNomePredio()});

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnEditar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnNovo = new javax.swing.JButton();
        txtIdApto = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        comboPredio = new javax.swing.JComboBox<>();
        comboBloco = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        txtNumeroApto = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtApto = new javax.swing.JTable();

        setClosable(true);
        setTitle("Cadastro Apartamento");

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sindicoonline/Icones/edit4545.png"))); // NOI18N
        btnEditar.setToolTipText("Editar Cadastro");
        btnEditar.setEnabled(false);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sindicoonline/Icones/delete4545.png"))); // NOI18N
        btnExcluir.setToolTipText("Excluir Cadastro");
        btnExcluir.setEnabled(false);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        jLabel1.setText("Numero:");

        jLabel4.setText("Codigo:");

        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sindicoonline/Icones/add4545.png"))); // NOI18N
        btnNovo.setToolTipText("Novo Cadastro");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        txtIdApto.setToolTipText("Codigo referente ao cadastro.");
        txtIdApto.setEnabled(false);

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sindicoonline/Icones/salvar4545.png"))); // NOI18N
        btnSalvar.setToolTipText("Salvar");
        btnSalvar.setEnabled(false);
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        comboPredio.setToolTipText("Selecione o predio correspondente.");
        comboPredio.setEnabled(false);
        comboPredio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comboPredioMouseClicked(evt);
            }
        });
        comboPredio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboPredioActionPerformed(evt);
            }
        });
        comboPredio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                comboPredioKeyPressed(evt);
            }
        });

        comboBloco.setToolTipText("Selecione o bloco correspondente.");
        comboBloco.setEnabled(false);
        comboBloco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                comboBlocoKeyPressed(evt);
            }
        });

        jLabel2.setText("Predio:");

        jLabel3.setText("Bloco:");

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sindicoonline/Icones/cancelar Original.png"))); // NOI18N
        btnCancelar.setToolTipText("Cancelar");
        btnCancelar.setEnabled(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        txtNumeroApto.setToolTipText("Digite numeros.");
        txtNumeroApto.setEnabled(false);
        txtNumeroApto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNumeroAptoKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboPredio, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIdApto, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jLabel1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jLabel3))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNumeroApto, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboBloco, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtIdApto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(txtNumeroApto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboBloco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(comboPredio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jtApto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Codigo APTO", "Numero APTO", "Nome Bloco", "Nome Predio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtApto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtAptoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtApto);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 525, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed

        if (txtIdApto.equals(null)) {
            JOptionPane.showMessageDialog(null, "Escolha um item para editar na tabela abaixo");
        } else {
            txtNumeroApto.setEnabled(true);
            btnSalvar.setEnabled(true);
            btnNovo.setEnabled(false);
            btnEditar.setEnabled(false);
            btnExcluir.setEnabled(false);
            txtNumeroApto.requestFocus();
            comboBloco.setEnabled(true);
            comboPredio.setEnabled(true);
            btnCancelar.setEnabled(true);
            btnExcluir.setEnabled(false);
            opSAlvarEditar = "editar";
            jtApto.setEnabled(false);
            txtNumeroApto.setEnabled(true);

        }

    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        jtApto.setEnabled(false);
        int resposta = JOptionPane.showConfirmDialog(null, "Deseja realmente EXCLUIR?", title, JOptionPane.YES_NO_OPTION);

        if (resposta == JOptionPane.YES_OPTION) {
            try {
                Apto apto = new Apto();
                AptoDAO daoApto = new AptoDAO();
                apto.setIdApto(Integer.valueOf(txtIdApto.getText()));
                daoApto.deleteApto(apto);
                JOptionPane.showMessageDialog(null, "Apto excluido com sucesso.");
            } catch (Exception e) {
            }

            txtNumeroApto.setEnabled(false);
            btnSalvar.setEnabled(false);
            btnNovo.setEnabled(true);
            btnEditar.setEnabled(false);
            btnExcluir.setEnabled(false);
            btnNovo.requestFocus();
            comboBloco.setEnabled(false);
            comboPredio.setEnabled(false);
            btnCancelar.setEnabled(false);
            txtNumeroApto.setText(null);
            txtIdApto.setText(null);
            btnNovo.requestFocus();
            txtNumeroApto.setEnabled(false);
            lerTabela();

        }
        jtApto.setEnabled(true);
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed

        // TODO add your handling code here:
        txtNumeroApto.setEnabled(true);
        txtNumeroApto.setText("");
        txtNumeroApto.setEnabled(true);
        btnSalvar.setEnabled(true);
        btnNovo.setEnabled(false);
        btnEditar.setEnabled(false);
        btnExcluir.setEnabled(false);
        txtNumeroApto.requestFocus();
        comboBloco.setEnabled(true);
        comboPredio.setEnabled(true);
        btnCancelar.setEnabled(true);
        opSAlvarEditar = "salvar";
        jtApto.setEnabled(false);
        txtNumeroApto.requestFocus();
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed

        Apto apto = new Apto();
        AptoDAO daoApto = new AptoDAO();
        Bloco b = new Bloco();
        Utilidades util = new Utilidades();

        int codPredio = util.achaCodigoPredio((String) comboPredio.getSelectedItem());
        int codBloco = util.achaCodigoBloco((String) comboBloco.getSelectedItem(), codPredio);

        b.setIdBloco(codBloco);

        apto.setNumeroApto(Integer.valueOf(txtNumeroApto.getText()));
        apto.setBloco(b);

        try {

            if (opSAlvarEditar.equals("salvar")) {
                daoApto.adicionarApto(apto);
                JOptionPane.showMessageDialog(null, "Apartamento salvo com sucesso!");
            } else {
                apto.setIdApto(Integer.valueOf(txtIdApto.getText()));
                daoApto.updateApto(apto);
                JOptionPane.showMessageDialog(null, "Apartamento alterado com sucesso!");
            }

            txtNumeroApto.setEnabled(false);
            btnSalvar.setEnabled(false);
            btnNovo.setEnabled(true);
            btnEditar.setEnabled(true);
            btnExcluir.setEnabled(true);
            btnNovo.requestFocus();
            comboBloco.setEnabled(false);
            comboPredio.setEnabled(false);
            btnCancelar.setEnabled(false);
            txtNumeroApto.setEnabled(false);
            btnNovo.requestFocus();
            jtApto.setEnabled(true);
            lerTabela();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao Salvar" + e);
        }

    }//GEN-LAST:event_btnSalvarActionPerformed

    private void comboPredioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboPredioMouseClicked

    }//GEN-LAST:event_comboPredioMouseClicked

    private void comboPredioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboPredioActionPerformed
        populaELimpa();     // TODO add your handling code here:
    }//GEN-LAST:event_comboPredioActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed

        int resposta = JOptionPane.showConfirmDialog(null, "Deseja realmente cancelar?", title, JOptionPane.YES_NO_OPTION);
        if (resposta == JOptionPane.YES_OPTION) {
            txtNumeroApto.setEnabled(false);
            btnSalvar.setEnabled(false);
            btnNovo.setEnabled(true);
            btnEditar.setEnabled(true);
            btnExcluir.setEnabled(true);
            btnNovo.requestFocus();
            comboBloco.setEnabled(false);
            comboPredio.setEnabled(false);
            btnCancelar.setEnabled(false);

        }

    }//GEN-LAST:event_btnCancelarActionPerformed

    private void comboPredioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_comboPredioKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            comboBloco.requestFocus();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_comboPredioKeyPressed

    private void comboBlocoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_comboBlocoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btnSalvar.requestFocus();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_comboBlocoKeyPressed

    private void jtAptoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtAptoMouseClicked
        txtIdApto.setText(jtApto.getValueAt(jtApto.getSelectedRow(), 0).toString());
        txtNumeroApto.setText(jtApto.getValueAt(jtApto.getSelectedRow(), 1).toString());
        comboBloco.setEditable(true);
        comboBloco.setEnabled(true);
        comboPredio.setEditable(true);
        comboPredio.setEnabled(true);
        comboBloco.setSelectedItem(jtApto.getValueAt(jtApto.getSelectedRow(), 2).toString());
        comboPredio.setSelectedItem(jtApto.getValueAt(jtApto.getSelectedRow(), 3).toString());
        comboBloco.setEditable(false);
        comboBloco.setEnabled(false);
        comboPredio.setEditable(false);
        comboPredio.setEnabled(false);

        btnEditar.setEnabled(true);
        btnExcluir.setEnabled(true);
    }//GEN-LAST:event_jtAptoMouseClicked

    private void txtNumeroAptoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumeroAptoKeyPressed
       if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            comboPredio.requestFocus();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroAptoKeyPressed

    public void populaComboPredio() {
        PreparedStatement stmt = null;
        Connection con = Conexao.getConnection();
        ResultSet rs = null;
        Utilidades util = new Utilidades();
        try {
            stmt = con.prepareStatement("SELECT * FROM predio");
            rs = stmt.executeQuery();
            while (rs.next()) {
//                Esse funciona q é um abeleza.
                comboPredio.addItem(rs.getObject(2));
            }
        } catch (Exception e) {
        }

    }

    public void populaComboBloco(int predio) {
        PreparedStatement stmt = null;
        Connection con = Conexao.getConnection();
        ResultSet rs = null;
        try {
            stmt = con.prepareStatement("SELECT * FROM bloco where idPredio = '" + predio + "'");
            rs = stmt.executeQuery();
            while (rs.next()) {
//                Esse funciona q é um abeleza.
                comboBloco.addItem(rs.getObject(2));
            }
        } catch (Exception e) {
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<Object> comboBloco;
    private javax.swing.JComboBox<Object> comboPredio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtApto;
    private javax.swing.JTextField txtIdApto;
    private javax.swing.JTextField txtNumeroApto;
    // End of variables declaration//GEN-END:variables
}
