/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.sindicoonline.frm;

import br.com.sindicoonline.DAO.Apto;
import br.com.sindicoonline.DAO.AptoDAO;
import br.com.sindicoonline.DAO.Bloco;
import br.com.sindicoonline.DAO.Conexao;
import br.com.sindicoonline.DAO.Morador;
import br.com.sindicoonline.DAO.MoradorDAO;
import br.com.sindicoonline.DAO.Predio;
import br.com.sindicoonline.DAO.PredioDAO;
import br.com.sindicoonline.Utilits.Utilidades;
import br.com.sindicoonline.Utilits.ValidarCPF;
import static br.com.sindicoonline.Utilits.ValidarCPF.isCPF;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author klebe
 */
public class frmMorador extends javax.swing.JInternalFrame {

    String opSAlvarEditar = "editar";
    int nPredio = 0;
    int nBloco = 0;

    public frmMorador() {
        initComponents();
        lerTabela();

    }

    public void lerTabela() {

        DefaultTableModel modelo = (DefaultTableModel) jtMorador.getModel();
        modelo.setNumRows(0);
        Morador morador = new Morador();
        MoradorDAO daoMorador = new MoradorDAO();

        for (Morador m : daoMorador.readMoradorListaComNome(morador)) {
            modelo.addRow(new Object[]{
                m.getIdMorador(),
                m.getNomeMorador(),
                m.getCpfMorador(),
                m.getApto().getNumeroApto(),
                m.getBloco().getNumeroBloco(),
                m.getPredio().getNomePredio(),
                m.getLoginMorador(),
                m.getSenhaMorador()});

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnEditar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        txtNomeMorador = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnNovo = new javax.swing.JButton();
        txtIdMorador = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        comboPredio = new javax.swing.JComboBox<>();
        comboBloco = new javax.swing.JComboBox<>();
        comboApto = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCPF = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtSenha = new javax.swing.JPasswordField();
        btnCancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtMorador = new javax.swing.JTable();

        setClosable(true);
        setTitle("Cadastro Morador");

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sindicoonline/Icones/edit4545.png"))); // NOI18N
        btnEditar.setToolTipText("Editar Cadastro");
        btnEditar.setEnabled(false);
        btnEditar.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                btnEditarAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sindicoonline/Icones/delete4545.png"))); // NOI18N
        btnExcluir.setToolTipText("Excluir Cadastro");
        btnExcluir.setEnabled(false);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        txtNomeMorador.setToolTipText("Digite o nome do morador.");
        txtNomeMorador.setEnabled(false);
        txtNomeMorador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNomeMoradorKeyPressed(evt);
            }
        });

        jLabel1.setText("Nome:");

        jLabel4.setText("Codigo:");

        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sindicoonline/Icones/add4545.png"))); // NOI18N
        btnNovo.setToolTipText("Novo Cadastro");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        txtIdMorador.setToolTipText("Codigo referente ao cadastro.");
        txtIdMorador.setEnabled(false);

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sindicoonline/Icones/salvar4545.png"))); // NOI18N
        btnSalvar.setToolTipText("Salvar cadastro.");
        btnSalvar.setEnabled(false);
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        comboPredio.setToolTipText("Selecione o predio correspondente.");
        comboPredio.setEnabled(false);
        comboPredio.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                comboPredioPopupMenuWillBecomeVisible(evt);
            }
        });
        comboPredio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comboPredioMouseClicked(evt);
            }
        });
        comboPredio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboPredioActionPerformed(evt);
            }
        });
        comboPredio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                comboPredioKeyPressed(evt);
            }
        });

        comboBloco.setToolTipText("Selecione o bloco correspondente.");
        comboBloco.setEnabled(false);
        comboBloco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comboBlocoMouseClicked(evt);
            }
        });
        comboBloco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBlocoActionPerformed(evt);
            }
        });
        comboBloco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                comboBlocoKeyPressed(evt);
            }
        });

        comboApto.setToolTipText("Selecione o apartamento correspondente.");
        comboApto.setEnabled(false);
        comboApto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboAptoActionPerformed(evt);
            }
        });
        comboApto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                comboAptoKeyPressed(evt);
            }
        });

        jLabel2.setText("Predio:");

        jLabel3.setText("Bloco");

        jLabel5.setText("Apto:");

        jLabel6.setText("CPF:");

        try {
            txtCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCPF.setToolTipText("Digite um CPF válido.");
        txtCPF.setEnabled(false);
        txtCPF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCPFKeyPressed(evt);
            }
        });

        jLabel7.setText("Usuario:");

        txtUsuario.setToolTipText("Usar apenas letras minusculas.");
        txtUsuario.setEnabled(false);
        txtUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUsuarioKeyPressed(evt);
            }
        });

        jLabel8.setText("Senha:");

        txtSenha.setToolTipText("Utilizar senha forte.");
        txtSenha.setEnabled(false);
        txtSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSenhaKeyPressed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sindicoonline/Icones/cancelar Original.png"))); // NOI18N
        btnCancelar.setToolTipText("Canelar ação.");
        btnCancelar.setEnabled(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(txtIdMorador, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(35, 35, 35)
                                        .addComponent(jLabel1))
                                    .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtNomeMorador, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btnNovo)
                                .addGap(35, 35, 35)
                                .addComponent(btnEditar)
                                .addGap(35, 35, 35)
                                .addComponent(btnExcluir)
                                .addGap(35, 35, 35)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnSalvar)
                                    .addComponent(btnCancelar))))
                        .addContainerGap(218, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboPredio, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboBloco, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comboApto, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnNovo)
                        .addComponent(btnEditar)
                        .addComponent(btnExcluir))
                    .addComponent(btnCancelar))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtIdMorador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(txtNomeMorador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSalvar)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(comboPredio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(comboBloco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(comboApto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 680, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 234, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(6, 6, 6)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jtMorador.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "CODIGO MORADOR", "NOME MORADOR", "CPF", "APTO", "BLOCO", "PREDIO", "USUARIO", "SENHA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtMorador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtMoradorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtMorador);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 670, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        if (txtIdMorador.equals(null)) {
            JOptionPane.showMessageDialog(null, "Selecionar algum morador.");
        } else {
limpaEPopulaBloco();


            opSAlvarEditar = "editar";
            comboApto.setEditable(false);
            btnSalvar.setEnabled(true);
            btnNovo.setEnabled(false);
            btnEditar.setEnabled(false);
            btnExcluir.setEnabled(false);
            txtNomeMorador.setEnabled(true);
            txtNomeMorador.requestFocus();
            txtCPF.setEnabled(true);
            txtUsuario.setEnabled(true);
            txtSenha.setEnabled(true);
            comboPredio.setEnabled(true);
            comboBloco.setEnabled(true);
            comboApto.setEnabled(true);
            btnCancelar.setEnabled(true);
        }


    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed

        if (txtIdMorador.equals(null)) {
            JOptionPane.showMessageDialog(null, "Selecionar algum morador.");
        } else {

            int resposta = JOptionPane.showConfirmDialog(null, "Deseja realmente excluir?", title, JOptionPane.YES_NO_OPTION);
            if (resposta == JOptionPane.YES_OPTION) {

                try {
                    Morador morador = new Morador();
                    MoradorDAO daoMorador = new MoradorDAO();
                    morador.setIdMorador(Integer.valueOf(txtIdMorador.getText()));
                    JOptionPane.showMessageDialog(this, "Morador excluido com ");
                    daoMorador.deleteMorador(morador);

                    txtIdMorador.setText(null);
                    txtNomeMorador.setText(null);
                    txtCPF.setText(null);
                    txtUsuario.setText(null);
                    txtSenha.setText(null);

                    lerTabela();

                } catch (Exception e) {
                }

            }

        }
        btnCancelar.setEnabled(false);

    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        // TODO add your handling code here:

        populaComboPredio();
        limpaEPopulaBloco();
        limpaEPopulaApto();
        comboApto.setEditable(false);
        btnSalvar.setEnabled(true);
        btnNovo.setEnabled(false);
        btnEditar.setEnabled(false);
        btnExcluir.setEnabled(false);
        txtNomeMorador.setEnabled(true);
        txtNomeMorador.requestFocus();
        txtCPF.setEnabled(true);
        txtUsuario.setEnabled(true);
        txtSenha.setEnabled(true);
        comboPredio.setEnabled(true);
        comboBloco.setEnabled(true);
        comboApto.setEnabled(true);
        txtIdMorador.setText(null);
        txtNomeMorador.setText(null);
        txtCPF.setText(null);
        txtUsuario.setText(null);
        txtSenha.setText(null);
        opSAlvarEditar = "novo";
        btnCancelar.setEnabled(true);


    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed

        Morador morador = new Morador();
        MoradorDAO daoMorador = new MoradorDAO();
        Apto ap = new Apto();
        Utilidades util = new Utilidades();

        int codPredio = util.achaCodigoPredio((String) comboPredio.getSelectedItem());
        System.out.println("Cod Predio " + codPredio);
        int codBloco = util.achaCodigoBloco((String) comboBloco.getSelectedItem(), codPredio);
        System.out.println("Cod Bloco " + codBloco);
   
        Integer codApto = util.achaCodigoApto((Integer) comboApto.getSelectedItem(), codBloco);
        System.out.println("codApto " + codApto);

        morador.setNomeMorador(txtNomeMorador.getText());
        morador.setCpfMorador(txtCPF.getText().replaceAll("[.-]", ""));
        morador.setLoginMorador(txtUsuario.getText());
        morador.setSenhaMorador(txtSenha.getText());

        ap.setIdApto(codApto);

        morador.setApto(ap);

        if (isCPF(txtCPF.getText().replaceAll("[.-]", ""))) {
            if (opSAlvarEditar.equals("novo")) {
                daoMorador.adicionarMorador(morador);
                JOptionPane.showMessageDialog(null, "Morador ADICIONADO com sucesso!");

                txtNomeMorador.setText("");
                txtIdMorador.setText("");
                txtCPF.setText("");
                txtSenha.setText("");
                txtUsuario.setText("");
                txtCPF.setEnabled(false);
                txtIdMorador.setEnabled(false);
                txtNomeMorador.setEnabled(false);
                txtSenha.setEnabled(false);
                txtUsuario.setEnabled(false);
                comboApto.setEnabled(false);
                comboBloco.setEnabled(false);
                comboPredio.setEnabled(false);
                btnNovo.setEnabled(true);
                btnCancelar.setEnabled(false);
                btnSalvar.setEnabled(false);

            } else {
                morador.setIdMorador(Integer.valueOf(txtIdMorador.getText()));
                daoMorador.updateApto(morador);
                JOptionPane.showMessageDialog(null, "Morador EDITADO com sucesso!");
                btnNovo.setEnabled(true);
                btnSalvar.setEnabled(false);
                btnCancelar.setEnabled(false);
                txtCPF.setEnabled(false);
                txtIdMorador.setEnabled(false);
                txtNomeMorador.setEnabled(false);
                txtSenha.setEnabled(false);
                txtUsuario.setEnabled(false);
                comboApto.setEnabled(false);
                comboBloco.setEnabled(false);
                comboPredio.setEnabled(false);

            }
        } else {
            JOptionPane.showMessageDialog(null, "Digite um CPF valido.");
        }

        lerTabela();
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void comboPredioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboPredioActionPerformed
        if (opSAlvarEditar.equals("novo")) {

            limpaEPopulaBloco();
        }


    }//GEN-LAST:event_comboPredioActionPerformed

    private void comboBlocoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBlocoActionPerformed
        if (opSAlvarEditar.equals("novo")) {
            limpaEPopulaApto();
        } else {

        }
    }//GEN-LAST:event_comboBlocoActionPerformed

    private void jtMoradorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtMoradorMouseClicked
        txtIdMorador.setText(jtMorador.getValueAt(jtMorador.getSelectedRow(), 0).toString());
        txtNomeMorador.setText(jtMorador.getValueAt(jtMorador.getSelectedRow(), 1).toString());
        txtCPF.setText(jtMorador.getValueAt(jtMorador.getSelectedRow(), 2).toString());
        comboPredio.removeAllItems();
        populaComboPredio();
        comboPredio.setSelectedItem(jtMorador.getValueAt(jtMorador.getSelectedRow(), 5).toString());
        limpaEPopulaBloco();
        comboBloco.setSelectedItem(jtMorador.getValueAt(jtMorador.getSelectedRow(), 4).toString());
        comboApto.setEditable(true);

        populaComboSemFiltro();

        comboApto.setSelectedItem(jtMorador.getValueAt(jtMorador.getSelectedRow(), 3).toString());

//        String ap = jtMorador.getValueAt(jtMorador.getSelectedRow(), 3).toString();
//        System.out.println(ap);
//        comboApto.setSelectedItem(ap);
        txtUsuario.setText(jtMorador.getValueAt(jtMorador.getSelectedRow(), 6).toString());
        txtSenha.setText(jtMorador.getValueAt(jtMorador.getSelectedRow(), 7).toString());

        btnEditar.setEnabled(true);
        btnExcluir.setEnabled(true);

// TODO add your handling code here:
    }//GEN-LAST:event_jtMoradorMouseClicked

    private void comboPredioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboPredioMouseClicked


    }//GEN-LAST:event_comboPredioMouseClicked

    private void comboBlocoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboBlocoMouseClicked

    }//GEN-LAST:event_comboBlocoMouseClicked

    private void comboPredioPopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_comboPredioPopupMenuWillBecomeVisible
        // TODO add your handling code here:
    }//GEN-LAST:event_comboPredioPopupMenuWillBecomeVisible

    private void comboAptoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboAptoActionPerformed
//        if (opSAlvarEditar.equals("novo")) {
//            limpaEPopulaApto();
//        } else {
//            populaComboSemFiltro();
//        }      
    }//GEN-LAST:event_comboAptoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        int resposta = JOptionPane.showConfirmDialog(null, "Deseja realmente cancelar?", title, JOptionPane.YES_NO_OPTION);
        if (resposta == JOptionPane.YES_OPTION) {

            txtIdMorador.setEnabled(false);
            txtNomeMorador.setEnabled(false);
            txtCPF.setEnabled(false);
            txtSenha.setEnabled(false);
            txtUsuario.setEnabled(false);
            txtIdMorador.setText("");
            txtNomeMorador.setText("");
            txtIdMorador.setText("");
            txtCPF.setText("");
            txtSenha.setText("");
            txtUsuario.setText("");
            btnNovo.setEnabled(true);
            btnCancelar.setEnabled(false);
            btnEditar.setEnabled(false);
            btnExcluir.setEnabled(false);
            btnSalvar.setEnabled(false);
            comboApto.setEnabled(false);
            comboBloco.setEnabled(false);
            comboPredio.setEnabled(false);
        }
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnEditarAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_btnEditarAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarAncestorAdded

    private void txtNomeMoradorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeMoradorKeyPressed
               if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtCPF.requestFocus();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeMoradorKeyPressed

    private void txtCPFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCPFKeyPressed
               if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtUsuario.requestFocus();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtCPFKeyPressed

    private void txtUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuarioKeyPressed
               if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtSenha.requestFocus();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioKeyPressed

    private void txtSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSenhaKeyPressed
               if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            comboPredio.requestFocus();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtSenhaKeyPressed

    private void comboPredioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_comboPredioKeyPressed
               if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            comboBloco.requestFocus();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_comboPredioKeyPressed

    private void comboBlocoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_comboBlocoKeyPressed
               if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            comboApto.requestFocus();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_comboBlocoKeyPressed

    private void comboAptoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_comboAptoKeyPressed
               if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btnSalvar.requestFocus();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_comboAptoKeyPressed

    public void limpaEPopulaBloco() {
        try {

            Utilidades util = new Utilidades();

            comboBloco.removeAllItems();
            int codPredio = util.achaCodigoPredio((String) comboPredio.getSelectedItem());

            populaComboBloco(codPredio);
        } catch (Exception e) {

        }
    }

    public void limpaEPopulaApto() {
        try {

            Utilidades util = new Utilidades();

            int codPredio = util.achaCodigoPredio((String) comboPredio.getSelectedItem());
            int codBloco = util.achaCodigoBloco((String) comboBloco.getSelectedItem(), codPredio);

            comboApto.removeAllItems();
            populaComboApto(codBloco);
        } catch (Exception e) {

        }

    }

    public void populaComboSemFiltro() {
        try {
            Utilidades util = new Utilidades();

            int codPredio = util.achaCodigoPredio((String) comboPredio.getSelectedItem());
            int codBloco = util.achaCodigoBloco((String) comboBloco.getSelectedItem(), codPredio);
            comboApto.removeAllItems();
            populaComboAptoTodos(codBloco);

        } catch (Exception e) {

        }

    }

    public void populaComboPredio() {

        PreparedStatement stmt = null;
        Connection con = Conexao.getConnection();
        ResultSet rs = null;
        try {
            stmt = con.prepareStatement("SELECT * FROM predio");
            rs = stmt.executeQuery();
            while (rs.next()) {
//                Esse funciona q é um abeleza.
                comboPredio.addItem(rs.getObject(2));

            }
            con.close();
        } catch (Exception e) {

        }

    }

    public void populaComboBloco(int predio) {
        PreparedStatement stmt = null;
        Connection con = Conexao.getConnection();
        ResultSet rs = null;

        try {
            stmt = con.prepareStatement("SELECT * FROM bloco where idPredio = '" + predio + "'");
            rs = stmt.executeQuery();
            while (rs.next()) {
//                Esse funciona q é um abeleza.
                comboBloco.addItem(rs.getObject(2));

            }
            con.close();
        } catch (Exception e) {

        }

    }

    public void populaComboApto(int bloco) {
        PreparedStatement stmt = null;
        Connection con = Conexao.getConnection();
        ResultSet rs = null;
        try {
            stmt = con.prepareStatement("SELECT numeroApto FROM apto where idBloco = '" + bloco + "' and not exists (select idApto from morador where morador.idApto = apto.idApto)");
            rs = stmt.executeQuery();
            while (rs.next()) {
//                Esse funciona q é um abeleza.
                comboApto.addItem(rs.getObject(1));

            }
            con.close();
        } catch (Exception e) {
        }

    }

    public int achaCodigoPredio(String nome) {
        PreparedStatement stmt = null;
        Connection con = Conexao.getConnection();
        ResultSet rs = null;
        try {
            stmt = con.prepareStatement("SELECT idPredio FROM predio where nomePredio = '" + nome + "'");
            rs = stmt.executeQuery();
            while (rs.next()) {
//                Esse funciona q é um abeleza.
                int n = (int) rs.getObject(1);
                return n;

            }
            con.close();
        } catch (Exception e) {

        }
        return 0;

    }

    public int achaCodigoBloco(String nome) {
        PreparedStatement stmt = null;
        Connection con = Conexao.getConnection();
        ResultSet rs = null;
        try {
            stmt = con.prepareStatement("SELECT idBloco FROM bloco where nomeBloco = '" + nome + "' and idPredio = " + nPredio);
            rs = stmt.executeQuery();
            while (rs.next()) {
//                Esse funciona q é um abeleza.
                int n = (int) rs.getObject(1);
                return n;

            }
            con.close();
        } catch (Exception e) {

        }

        return 0;
    }

    public void populaComboAptoTodos(int bloco) {
        PreparedStatement stmt = null;
        Connection con = Conexao.getConnection();
        ResultSet rs = null;
        try {
            stmt = con.prepareStatement("SELECT numeroApto FROM apto where idBloco = '" + bloco + "'");
            rs = stmt.executeQuery();
            while (rs.next()) {
//                Esse funciona q é um abeleza.
                comboApto.addItem(rs.getObject(1));

            }
            con.close();
        } catch (Exception e) {
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<Object> comboApto;
    private javax.swing.JComboBox<Object> comboBloco;
    private javax.swing.JComboBox<Object> comboPredio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtMorador;
    private javax.swing.JFormattedTextField txtCPF;
    private javax.swing.JTextField txtIdMorador;
    private javax.swing.JTextField txtNomeMorador;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
