/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.sindicoonline.frm;

import br.com.sindicoonline.DAO.Predio;
import br.com.sindicoonline.DAO.PredioDAO;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

public final class frmPredio extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadastroPredio
     */
    public frmPredio() {
        initComponents();
        DefaultTableModel modelo = (DefaultTableModel) jTPredio.getModel();
        jTPredio.setRowSorter(new TableRowSorter(modelo));
        
        lerTabela();
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnEditar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        txtNomePredio = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnNovo = new javax.swing.JButton();
        txtIdPredio = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTPredio = new javax.swing.JTable();

        setClosable(true);
        setTitle("Cadastro de Predios");

        btnEditar.setText("Editar Cadastro");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir Cadastro");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        txtNomePredio.setEnabled(false);

        jLabel1.setText("Nome:");

        jLabel4.setText("Codigo:");

        btnNovo.setText("Novo Cadastro");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        txtIdPredio.setEnabled(false);

        btnSalvar.setText("Salvar");
        btnSalvar.setEnabled(false);
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtIdPredio, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(35, 35, 35)
                            .addComponent(jLabel1)
                            .addGap(18, 18, 18)
                            .addComponent(txtNomePredio, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(btnNovo)
                            .addGap(32, 32, 32)
                            .addComponent(btnEditar)
                            .addGap(18, 18, 18)
                            .addComponent(btnExcluir))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovo)
                    .addComponent(btnEditar)
                    .addComponent(btnExcluir)
                    .addComponent(btnSair))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtIdPredio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(txtNomePredio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSalvar)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jTPredio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOME"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTPredio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTPredioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTPredio);
        if (jTPredio.getColumnModel().getColumnCount() > 0) {
            jTPredio.getColumnModel().getColumn(0).setMinWidth(40);
            jTPredio.getColumnModel().getColumn(0).setMaxWidth(40);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public int testarEditarSalvar = 0;

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        // TODO add your handling code here:
        txtNomePredio.setEnabled(true);

        btnSalvar.setEnabled(true);
        btnNovo.setEnabled(false);
        btnEditar.setEnabled(false);
        btnExcluir.setEnabled(false);
        txtNomePredio.requestFocus();

    }//GEN-LAST:event_btnNovoActionPerformed


    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed

        Predio predio = new Predio();
        PredioDAO daoPredio = new PredioDAO();
        if (testarEditarSalvar == 0) {
            try {

                predio.setNomePredio(txtNomePredio.getText());

                if (txtNomePredio.getText() == null || txtNomePredio.getText().trim().equals("")) {
                    JOptionPane.showMessageDialog(null, "Digite o nome do Predio");
                } else {
                    daoPredio.adicionarPredio(predio);
                    System.out.println("Salvo com sucesso.");
                    JOptionPane.showMessageDialog(null, "Registro savo com sucesso.");

                    txtNomePredio.setEnabled(false);
                    btnSalvar.setEnabled(false);
                    btnNovo.setEnabled(true);
                    txtNomePredio.setText(null);
                    btnEditar.setEnabled(true);
                    btnExcluir.setEnabled(true);
                }

            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(null, "Digite um valor valido no campo (R$).");
            } catch (Exception ex) {
                System.out.println("ERRO ao SALVAR" + ex);
            }
        } else if (testarEditarSalvar == 1) {

            try {
                predio.setIdPredio(Integer.parseInt(txtIdPredio.getText()));
                predio.setNomePredio(txtNomePredio.getText());

//            double valor = Double.parseDouble(txtValorCondominioPredio.getText().replace(",", "."));
//            predio.setValorCondominio(valor);
                if (txtNomePredio.getText() == null || txtNomePredio.getText().trim().equals("")) {
                    JOptionPane.showMessageDialog(null, "Digite o nome do Predio");
                } else {
                    daoPredio.updatePredio(predio);
                    System.out.println("Salvo com sucesso.");
                    JOptionPane.showMessageDialog(null, "Registro alterado com sucesso.");

                    txtNomePredio.setEnabled(false);

                    btnSalvar.setEnabled(false);
                    btnNovo.setEnabled(true);
                    txtIdPredio.setText(null);

                    txtNomePredio.setText(null);

                    btnEditar.setEnabled(true);
                    btnExcluir.setEnabled(true);
                }

            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(null, "Digite um valor valido no campo (R$).");
            } catch (Exception ex) {
                System.out.println("ERRO ao SALVAR" + ex);
            }

        }

        lerTabela();

        testarEditarSalvar = 0;
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void jTPredioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTPredioMouseClicked
        txtIdPredio.setText(jTPredio.getValueAt(jTPredio.getSelectedRow(), 0).toString());
        txtNomePredio.setText(jTPredio.getValueAt(jTPredio.getSelectedRow(), 1).toString());

    }//GEN-LAST:event_jTPredioMouseClicked

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        testarEditarSalvar = 1;
        try {
            if (jTPredio.getValueAt(jTPredio.getSelectedRow(), 0).toString() != "") {
                // TODO add your handling code here:
                txtNomePredio.setEnabled(true);

                btnSalvar.setEnabled(true);
                btnNovo.setEnabled(false);
                btnEditar.setEnabled(false);
                btnExcluir.setEnabled(false);
                txtNomePredio.requestFocus();
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Selecione algum item");
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        Predio predio = new Predio();
        PredioDAO daoPredio = new PredioDAO();

        try {
            if (jTPredio.getValueAt(jTPredio.getSelectedRow(), 0).toString() != "") {
                int resposta = JOptionPane.showConfirmDialog(null, "Deseja realmente excluir?", title, JOptionPane.YES_NO_OPTION);
                if (resposta == JOptionPane.YES_OPTION) {
                    predio.setIdPredio(Integer.parseInt(txtIdPredio.getText()));
                    daoPredio.deletePredio(predio);
                } 
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Selecione algum item para excluir");
        }
        lerTabela();

    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnSairActionPerformed

    public void lerTabela() {

        DefaultTableModel modelo = (DefaultTableModel) jTPredio.getModel();
        modelo.setNumRows(0);
        PredioDAO pdao = new PredioDAO();
        Predio predio = new Predio();
        

        for (Predio p : pdao.readPredioLista(predio)) {
            modelo.addRow(new Object[]{
                p.getIdPredio(),
                p.getNomePredio(),});

        }

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTPredio;
    private javax.swing.JTextField txtIdPredio;
    private javax.swing.JTextField txtNomePredio;
    // End of variables declaration//GEN-END:variables
}
