/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.sindicoonline.frm;

import static br.com.sindicoonline.frm.frmPrincipal.painelPrincipal;

/**
 *
 * @author klebe
 */
public class frmSindico extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmSindico
     */
    public frmSindico() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAddMorador = new javax.swing.JButton();
        btnApto = new javax.swing.JButton();
        btnAddBloco = new javax.swing.JButton();
        btnAddPredio = new javax.swing.JButton();
        btnAvisos = new javax.swing.JButton();

        setClosable(true);
        setTitle("Area do Sindico");

        btnAddMorador.setText("Morador");
        btnAddMorador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddMoradorActionPerformed(evt);
            }
        });

        btnApto.setText("APTO");
        btnApto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAptoActionPerformed(evt);
            }
        });

        btnAddBloco.setText("Bloco");
        btnAddBloco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddBlocoActionPerformed(evt);
            }
        });

        btnAddPredio.setText("Predio");
        btnAddPredio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPredioActionPerformed(evt);
            }
        });

        btnAvisos.setText("Avisos");
        btnAvisos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvisosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnApto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnAddBloco, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnAddPredio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnAddMorador, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
            .addComponent(btnAvisos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAddPredio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAddBloco)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnApto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAddMorador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAvisos)
                .addContainerGap(345, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddMoradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddMoradorActionPerformed
        frmMorador cadMorador = new frmMorador();
        painelPrincipal.add(cadMorador);
        cadMorador.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddMoradorActionPerformed

    private void btnAptoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAptoActionPerformed
        frmApto cadApto = new frmApto();
        painelPrincipal.add(cadApto);
        cadApto.setVisible(true);
    }//GEN-LAST:event_btnAptoActionPerformed

    private void btnAddBlocoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddBlocoActionPerformed
        frmBloco cadBloco = new frmBloco();
        painelPrincipal.add(cadBloco);
        cadBloco.setVisible(true);
    }//GEN-LAST:event_btnAddBlocoActionPerformed

    private void btnAddPredioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPredioActionPerformed

        frmPredio cadastroPredio = new frmPredio();
        painelPrincipal.add(cadastroPredio);
        cadastroPredio.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddPredioActionPerformed

    private void btnAvisosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvisosActionPerformed
        frmAvisosSindico sindico = new frmAvisosSindico();
           painelPrincipal.add(sindico);
        sindico.setVisible(true);
    }//GEN-LAST:event_btnAvisosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddBloco;
    private javax.swing.JButton btnAddMorador;
    private javax.swing.JButton btnAddPredio;
    private javax.swing.JButton btnApto;
    private javax.swing.JButton btnAvisos;
    // End of variables declaration//GEN-END:variables
}
